import Anthropic from '@anthropic-ai/sdk'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

export async function POST(request) {
  try {
    const { clearance_text, readback_text, scenario_type } = await request.json()

    const message = await anthropic.messages.create({
      model: 'claude-haiku-4-5',
      max_tokens: 500,
      messages: [{
        role: 'user',
        content: `You are an expert FAA flight instructor and air traffic controller grading a pilot's ATC readback.

Scenario type: ${scenario_type === 'ground' ? 'Ground Control Taxi Clearance' : 'IFR Clearance Delivery'}

Original clearance issued by ATC:
"${clearance_text}"

Pilot's readback:
"${readback_text}"

CRITICAL — VOICE-TO-TEXT LENIENCY (apply this before anything else):
The readback text you receive is generated by voice-to-text software, which frequently mishears words. You MUST treat the readback as an approximation of what was actually spoken. Follow these rules strictly:
- "9" and "niner" are ALWAYS identical. Never penalize one vs the other.
- Any phonetically similar word must be accepted. Examples: "kelo" = "kilo", "9 or left" = "niner left", "climate" = "climb and maintain", "climeate" = "climb and maintain", "chapter" = "after", "the patcher" = "departure", "free quency" = "frequency", "to" = "two", "for" = "four"
- If a word sounds like it could be a mishearing of the correct word, accept it. Do not penalize voice-to-text errors under any circumstances.
- Single digit numbers and their spoken equivalents are always interchangeable: "9"="niner", "5"="five", "3"="tree", etc.

CRITICAL — SEQUENTIAL NUMBERS:
When you see numbers that appear to run together in the readback, always try to interpret them as separate clearance elements first.
- "two five zero one zero minutes" = flight level 250 AND 10 minutes after departure
- "flight level 2 5 0 1 0" = flight level 250 AND 10 minutes
- Always split sequential numbers into the most logical combination of clearance elements.

GRADING RULES:
1. CALLSIGN IS MANDATORY. The pilot must include their callsign EITHER at the beginning OR at the end of the readback. Both positions are equally acceptable and receive full credit. Only deduct points if the callsign is completely absent.
2. Do NOT penalize for omitting the ATC facility name. Not required.
3. Do NOT penalize for omitting the word "runway" before a runway number.
4. Do NOT penalize for omitting leading zeros on runway numbers.
5. Do NOT penalize for "taxi to" vs "taxi via" — this distinction is not required for a correct readback.
6. For IFR destination, the city name alone is ALWAYS full credit. "atlanta", "dallas", "phoenix" are all acceptable regardless of the full airport name. Never penalize for not saying the full airport name.
7. For 5-character waypoint fix names, accept any phonetic attempt. Voice-to-text cannot accurately spell fixes like ZELMO or BOARS. If the pilot attempted to say something in that position, give full credit.
8. Never mention which rule you applied. Never reference rule numbers or guidelines.
9. Never explain interpretations. Grade naturally as a flight instructor would.
10. Never compliment correct items. Only give feedback on genuine errors.
11. Keep feedback concise and direct, as a flight instructor speaking to a student.
12. For ground control, required elements: callsign, runway, taxiway route, hold short or crossing instructions.
13. For IFR, required elements: callsign, destination, routing, initial altitude, expect altitude and time, departure frequency, squawk code.

Return raw JSON only, no markdown:
{"score":85,"feedback":"Your feedback here."}`
      }]
    })

    const rawText = message.content[0].text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
    const result = JSON.parse(rawText)
    return Response.json(result)

  } catch (error) {
    console.error('Grade API error:', error)
    return Response.json({ error: error.message }, { status: 500 })
  }
}
